// <auto-generated />
using JobMatchBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace JobMatchBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521030001_ConvertContractDataToView")]
    partial class ConvertContractDataToView
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
