// <auto-generated />
using System;
using JobMatchBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobMatchBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423005703_AddContractsTable")]
    partial class AddContractsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobMatchBackend.Models.Entities.Application", b =>
                {
                    b.Property<int>("IdApplication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdApplication"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdJob")
                        .HasColumnType("int");

                    b.Property<Guid>("IdStudent")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("JobIdJob")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdApplication");

                    b.HasIndex("JobIdJob");

                    b.HasIndex("StudentId");

                    b.HasIndex("IdJob", "IdStudent")
                        .IsUnique()
                        .HasDatabaseName("IX_Application_Job_Student");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("JobMatchBackend.Models.Entities.Contract", b =>
                {
                    b.Property<int>("IdContract")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContract"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdApplication")
                        .HasColumnType("int");

                    b.Property<Guid>("IdCompany")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdJob")
                        .HasColumnType("int");

                    b.Property<Guid>("IdStudent")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdContract");

                    b.HasIndex("IdApplication")
                        .IsUnique();

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdJob");

                    b.HasIndex("IdStudent");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("JobMatchBackend.Models.Entities.Job", b =>
                {
                    b.Property<int>("IdJob")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJob"));

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdCompany")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdJob");

                    b.HasIndex("CompanyId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("JobMatchBackend.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Career")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("JobMatchBackend.Models.Entities.Application", b =>
                {
                    b.HasOne("JobMatchBackend.Models.Entities.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobIdJob");

                    b.HasOne("JobMatchBackend.Models.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Job");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JobMatchBackend.Models.Entities.Contract", b =>
                {
                    b.HasOne("JobMatchBackend.Models.Entities.Application", "Application")
                        .WithOne("Contract")
                        .HasForeignKey("JobMatchBackend.Models.Entities.Contract", "IdApplication")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobMatchBackend.Models.Entities.User", "Company")
                        .WithMany("CompanyContracts")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobMatchBackend.Models.Entities.Job", "Job")
                        .WithMany("Contracts")
                        .HasForeignKey("IdJob")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobMatchBackend.Models.Entities.User", "Student")
                        .WithMany("StudentContracts")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Company");

                    b.Navigation("Job");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JobMatchBackend.Models.Entities.Job", b =>
                {
                    b.HasOne("JobMatchBackend.Models.Entities.User", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("JobMatchBackend.Models.Entities.Application", b =>
                {
                    b.Navigation("Contract");
                });

            modelBuilder.Entity("JobMatchBackend.Models.Entities.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("JobMatchBackend.Models.Entities.User", b =>
                {
                    b.Navigation("CompanyContracts");

                    b.Navigation("StudentContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
