// <auto-generated />
using JobMatchBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace JobMatchBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521030000_FixMissingTableRenames")]
    partial class FixMissingTableRenames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
